name: Main Workflow

on:
  release

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          version: 12
          registry-url: https://npm.pkg.github.com/
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish
        if: github.event.prerelease == false
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets. NPM_AUTH_TOKEN }}
